### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by evansgelist** [Muddz/PixelShot#10]
```
else if (!Utils.isPermissionGranted(this.getAppContext())) {
            throw new SecurityException("Permission WRITE_EXTERNAL_STORAGE is missing");
        }
```
If I want to save to the internal memory of the app, this condition is redundant.
This condition must be removed.

**Comment by evansgelist** [comment]
ignore this

**Comment by Muddz** [comment]
This has been removed because it's should not be the responsibility of the library and because users now can set any path to save the files to, so this check won't work anymore
