### ISSUE TITLE
Rounded CardView problem

### ISSUE THREAD

**Issue by Letscoder** [Muddz/PixelShot#15]
Hello!

I'm trying to make screenshot of layout with rounded CardView inside.

`<androidx.cardview.widget.CardView     
                android:innerRadius="0dp"
                android:shape="ring"
                app:cardElevation="0dp"
                app:cardCornerRadius="75dp">`

It is rendered correctly on device, but is square on screenshot.Any idea how to fix it?

**Comment by Muddz** [comment]
Hi. Could you share the whole layout xml + the Pixelshot code?

**Comment by lzhgreat** [comment]
I also encounter this problem. I use a  cardview as container in my item layout, when I drag this item the shadow of the cardview disappear. then, I finde this method:

private Bitmap createDraggingItemImage(View v, NinePatchDrawable shadow) 

I thinke this method return a bitmap without this shadow ,meybe cause the problem.

**Comment by Letscoder** [comment]
> Hi. Could you share the whole layout xml + the Pixelshot code?

At first it seemed to me that the problem was in the CardView, but actually a blank card is working fine.
The problem appears when I place RecyclerView inside the card.

`<FrameLayout android:layout_width="wrap_content"
             android:layout_height="wrap_content"
             android:id="@+id/root_view"
             android:background="@android:color/white">

        <androidx.cardview.widget.CardView
                android:id="@+id/card_view"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:innerRadius="0dp"
                android:shape="ring"
                app:cardElevation="0dp"
                app:cardCornerRadius="75dp">

            <FrameLayout
                    android:layout_width="150dp"
                    android:layout_height="150dp">

                <androidx.recyclerview.widget.RecyclerView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:overScrollMode="never"
                        android:clickable="false"
                        android:focusable="false"
                        android:id="@+id/recycler_view"/>
                
            </FrameLayout>

        </androidx.cardview.widget.CardView>

</FrameLayout>`

Using library like this: `PixelShot.of(root_view).toPNG().save()`

How it is on screen:
![Screenshot_2019-08-20-14-17-56-039_color pallete republic from image generator](https://user-images.githubusercontent.com/13479402/63343137-ed287980-c355-11e9-8764-3de5a833962f.png)

How is is on screenshot:
![1566298966038](https://user-images.githubusercontent.com/13479402/63343163-ff0a1c80-c355-11e9-9f24-f9a12fa96d8f.png)

**Comment by Muddz** [comment]
@Letscoder I will take a look at it here in the weekend

**Comment by Muddz** [comment]
Hi @Letscoder. Have you managed to fix it?

**Comment by Letscoder** [comment]
No, it seems internal problem with canvas rendering, so it doesn't work even ouside of the library.I've just used Glide circle filter to resolve this.
