### ISSUE TITLE
Empty classes.jar

### ISSUE THREAD

**Issue by thewirelessguy** [Muddz/PixelShot#3]
I've imported the library via gradle, but the classes.jar from the library seems to be empty, which means the classes cannot be resolved in my project:

![screen shot 2018-09-21](https://user-images.githubusercontent.com/1661280/45854478-3e457d00-bd43-11e8-9322-5a239ee88382.png)

**Comment by Muddz** [comment]
@thewirelessguy Thanks! I'm looking on it now!

**Comment by Muddz** [comment]
@thewirelessguy It should have been fixed now. Can you confirm it?

**Comment by thewirelessguy** [comment]
Yes, thanks. I did need to Invalidate Caches/Restart for it to work. After the Gradle cache was clear it downloaded your latest changes.

**Comment by Muddz** [comment]
@thewirelessguy Great! Please just create another issue if something is wrong.
