### ISSUE TITLE
Resources not found during linkage

### ISSUE THREAD

**Issue by RomanAnchugov** [Muddz/PixelShot#6]
I have this kind of error when trying to sync project after adding implementation of your lib.

```
Android resource linking failed
Output:  
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.

.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:910: error: resource android:attr/fontVariationSettings not found.

.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:910: error: resource android:attr/ttcIndex not found.
error: failed linking references.
```

May be it's because of conflicts with another libs. I can send you a whole gradle file i you will need it

**Comment by Muddz** [comment]
The latest version 1.1.0 has been migrated to AndroidX. I suspect that may cause you the problem
Please try this version implementation 'com.muddzdev:pixelshot:1.0.0' 

The only difference between the two version is the AndroidX migration and some implementation of Exceptions

**Comment by Muddz** [comment]
@RomanAnchugov Great!
How are you using the library? which usecase?

**Comment by RomanAnchugov** [comment]
I've just tested it. It works perfectly. Great lib
