### ISSUE TITLE
Wrong logic for save file

### ISSUE THREAD

**Issue by evansgelist** [Muddz/PixelShot#9]
I want to save to the internal memory of the phone and this line does not allow me to do it
`File directory = new File(Environment.getExternalStorageDirectory(), path);`
Let the user decide where to save
`File directory = new File(path);`
thanks

**Comment by Muddz** [comment]
Hi. Yes this will be now implemented because of the new restrictions of AndroidQ. 
PixelShot will undergo a small refactoring. Stay tuned and thanks for the tip

**Comment by Muddz** [comment]
Hey @evansgelist The library has been under a bigger refactoring and your feature requests is now also included. Read more about the changes in the `readme`
